version: '3.8'

services:
  mysql:
    image: 'mysql:8.0'
    container_name: mysql_db
    restart: always
    ports:
      - '3307:3306'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}

  # admin interface for database
  adminer:
    depends_on:
      - mysql
    image: adminer
    container_name: adminer-db-interface
    restart: always
    ports:
      - 9000:8080

  cas:
    build:
      context: ./cas_auth
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - '8443:8443'

  ts-node-express:
    build:
      context: ./our-experience-app
      dockerfile: Dockerfile
      target: base
    depends_on:
      - mysql
      - cas
    volumes:
      - ./our-experience-app:/home/node/app
    container_name: ts-node-express
    expose:
      - '5000'
    ports:
      - '5000:5000'
    command: npm run dev
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
